#自用clash基础配置，自行导入添加机场订阅后即可，见下文标注“此处填写机场订阅”文字

mixed-port: 7890

tun:
    enable: true
    stack: system
    dns-hijack:
        - any:53
    auto-route: true
    auto-detect-interface: true

allow-lan: true
mode: rule
log-level: info
ipv6: false
udp: true
profile:
  store-fake-ip: true
external-controller: 0.0.0.0:9090

dns:
    enable: true
    ipv6: false
    enhanced-mode: fake-ip
    fake-ip-filter:
        - 'connect.rom.miui.com'
        - 'localhost.ptlogin2.qq.com'
        - '+.msftnsci.com'
        - '+.msftconnecttest.com'
        - '+.gstatic.com'
        - '+.stun.*.*'
        - '+.stun.*.*.*'
        - '+.stun.*.*.*.*'
        - '+.time.*'
        - '+.time.*.*'
        - '+.time.*.*.*'
        - '+.ntp.*'
        - '+.ntp.*.*'
        - '+.ntp.*.*.*'
    default-nameserver:
        - 114.114.114.114
        - 223.5.5.5
        - 119.29.29.29
        - 8.8.4.4
    nameserver:
        - https://dns.alidns.com/dns-query
        - https://doh.pub/dns-query

proxies:

p: &p
  type: http
  interval: 3600
  health-check:
    enable: true
    url: http://www.gstatic.com/generate_204
    interval: 600

c: &c
  type: http
  behavior: classical
  interval: 86400

pr: &pr
  type: select
  proxies:
    - 默认
    - 全部
    - random-auto
    - 香港
    - 台湾
    - 日本
    - 新加坡
    - 美国
    - DIRECT

proxy-providers:

#所有订阅机场节点
  All: &All
    <<: *p
    url: "  此处填写机场订阅  此处填写机场订阅  此处填写机场订阅  "
    path: ./all.yaml
   
#random-auto
  auto:
    <<: *All
    filter: (新加坡|🇸🇬|SG|Singapore|台|湾|TW|Taiwan|日|日本|🇯🇵|东京|JP|Japan|港|🇭🇰|HK|Hong|美|🇺🇲|US|States|American|欧|法|德|俄).*(?:.*1.0|0.2|0.3|0.5|0.6|0.8|1|1.5|2|3) 

#香港分组
  hk:
    <<: *All
    filter: "港|香港|hk|HK|hongkong|HongKong|🇭🇰"

#台湾分组
  tw:
    <<: *All
    filter: "台|台湾|tw|TW|taiwan|Taiwan"

#日本分组
  jp:
    <<: *All
    filter: "日|日本|jp|JP|japan|Japan|🇯🇵"
 
#新加坡分组
  sg:
    <<: *All
    filter: "新|新加坡|狮城|sg|SG|singapore|🇸🇬"

#美国分组
  us:
    <<: *All
    filter: "美|美国|us|US|USA|🇺🇸"

proxy-groups:

  - name: 默认
    type: select
    proxies:
      - 全部
      - random-auto
      - 香港
      - 台湾
      - 日本
      - 新加坡
      - 美国
      - DIRECT

#节点及策略

  - name: 全部
    type: select
    use:
      - All

  - name: random-auto
    type: url-test
    use:
      - auto

#Google

  - name: Google
    <<: *pr

#社交

  - name: Telegram
    <<: *pr

  - name: Instagram
    <<: *pr


#流媒体
        
  - name: YouTube
    <<: *pr
      
  - name: NETFLIX
    <<: *pr
      
  - name: Spotify
    <<: *pr
      
  - name: Apple
    <<: *pr

  - name: Microsoft
    <<: *pr


  - name: Unknownsite
    <<: *pr

#分隔，下面是地区分组

  - name: 香港
    type: url-test
    use:
      - hk

  - name: 台湾
    type: url-test
    use:
      - tw

  - name: 日本
    type: url-test
    use:
      - jp

  - name: 美国
    type: url-test
    use:
      - us

  - name: 新加坡
    type: url-test
    use:
      - sg


rule-providers:

  Google:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google.yaml"
    path: ./rule_providers/Google.yaml

  YouTube:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml"
    path: ./rule_providers/YouTube.yaml

  Telegram:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram.yaml"
    path: ./rule_providers/Telegram.yaml

  Netflix:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix.yaml"
    path: ./rule_providers/Netflix.yaml
    
  Spotify:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Spotify/Spotify.yaml"
    path: ./rule_providers/Spotify.yaml

  Apple:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple.yaml"
    path: ./ruleset/Apple.yaml

  Microsoft:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.yaml"
    path: ./ruleset/Microsoft.yaml


rules:
  - IP-CIDR,127.0.0.1/32,REJECT,no-resolve
  - RULE-SET,YouTube,YouTube
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Netflix,NETFLIX
  - RULE-SET,Google,Google
  - RULE-SET,Spotify,Spotify
  - RULE-SET,Apple,Apple
  - RULE-SET,Microsoft,Microsoft
  - GEOIP,CN,DIRECT
  - MATCH,Unknownsite. 
